#if !canImport(ObjectiveC)
import XCTest

extension RTPTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RTPTests = [
        ("testConnectionStop", testConnectionStop),
        ("testMemorySizes", testMemorySizes),
        ("testPacketInitWithData", testPacketInitWithData),
        ("testPacketizerIncrementOverflow", testPacketizerIncrementOverflow),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RTPTests.__allTests__RTPTests),
    ]
}
#endif
