name: Test

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test.yaml"
      - ".gitmodules"
      - "**.swift"
      - "Package.resolved"
  pull_request:
    paths:
      - ".github/workflows/test.yaml"
      - ".gitmodules"
      - "**.swift"
      - "Package.resolved"

jobs:
  test:
    name: Test
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Test
        run: swift test

      - name: Generate release build
        run: swift build -c release
